### ISSUE TITLE
MultiJson::ParseError

### ISSUE THREAD

**Issue by cloudrck** [RLovelett/rlovelett-ffmpeg#5]
I switched from streamio-ffmpeg to this version. Same code, but it seems to not work the same as the older version. My guess is that it's an issue with invalid JSON. Since streamio never used MultiJson to parse data. Are there any workarounds for this.

The line 257 in my app just loads the file 
```
movie = FFMPEG::Movie.new(ENV['STORE_DIR']+"/"+upload_file)
```
```
2015-07-19 22:00:10 - MultiJson::ParseError - Oj::ParseError:
	/usr/local/rvm/gems/ruby-2.1.5/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:19:in `load'
	/usr/local/rvm/gems/ruby-2.1.5/gems/multi_json-1.11.2/lib/multi_json.rb:119:in `load'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rlovelett-ffmpeg-1.1.1/lib/ffmpeg/movie.rb:28:in `initialize'
	/home/appdir/app.rb:257:in `new'
	/home/appdir/app.rb:257:in `block in <top (required)>'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack_csrf-2.5.0/lib/rack/csrf.rb:39:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/bundler/gems/rack-flash-006b6e4f7956/lib/rack/flash.rb:124:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
	/usr/local/rvm/gems/ruby-2.1.5/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/better_errors-2.1.1/lib/better_errors/middleware.rb:59:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/logger.rb:15:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:211:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `block in call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1795:in `synchronize'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:1486:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/usr/local/rvm/gems/ruby-2.1.5/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client'
	/usr/local/rvm/gems/ruby-2.1.5/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop'
	/usr/local/rvm/gems/ruby-2.1.5/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
	/usr/local/rvm/gems/ruby-2.1.5/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
	/usr/local/rvm/gems/ruby-2.1.5/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
	/usr/local/rvm/gems/ruby-2.1.5/bin/unicorn:23:in `load'
	/usr/local/rvm/gems/ruby-2.1.5/bin/unicorn:23:in `<main>'
	/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
	/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by cloudrck** [comment]
This appears to have been an issue with the outdated FFMPEG version on Ubuntu 12.04. Using the latest static binaries works as expected.

One question on the readme it has the line

```
FFMPEG.ffmpeg_binary = '/usr/local/bin/ffmpeg'
```

Should this be?

```
FFMPEG.ffprobe_binary = '/usr/local/bin/ffmpeg'
```

Also, since I uninstalled the Ubuntu's repository version, ruby looks in PATH which typically has /usr/local/bin in it. So it works without setting any variables.

**Comment by RLovelett** [comment]
@cloudrck I probably should update the README to be more explicit.

What it _should_ be is the fully qualified path to both binaries.

So on Linux/Unix system the way that I do that is with the `which` command. Something like:

```
$ which ffmpeg
$ which ffprobe
```

Then just fill in the path accordingly.

Also to address your last points, it _should_ work without specifying the full path as long as they can be found on the `PATH` environment variable of the user who owns the running process.

Hope that clears things up.
